# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_alpha_beta_cpp <- function(X, known_alpha, alpha) {
    .Call(`_LGCU_estimate_alpha_beta_cpp`, X, known_alpha, alpha)
}

monte_carlo_loop_cpp <- function(alpha, beta, alpha0_est, beta0_est, beta1, n_I, known_alpha, H_delta, H_plus, k_plus, K_l, delay, tau, max_iter = 1e4L) {
    .Call(`_LGCU_monte_carlo_loop_cpp`, alpha, beta, alpha0_est, beta0_est, beta1, n_I, known_alpha, H_delta, H_plus, k_plus, K_l, delay, tau, max_iter)
}

monte_carlo_loop_down_cpp <- function(alpha, beta, alpha0_est, beta0_est, beta1, n_I, known_alpha, H_delta, H_minus, k_minus, K_l, delay, tau, max_iter = 1e4L) {
    .Call(`_LGCU_monte_carlo_loop_down_cpp`, alpha, beta, alpha0_est, beta0_est, beta1, n_I, known_alpha, H_delta, H_minus, k_minus, K_l, delay, tau, max_iter)
}

